### ISSUE TITLE
Only four datasets can be found when read hdf5 file

### ISSUE THREAD

**Issue by absolutelyZero** [batchatco/go-native-netcdf#7] opened 2022-12-22 03:30 UTC
only four datasets can be found when read hdf5 file，but in fact, 68 datasets exist

Go debug :
![image](https://user-images.githubusercontent.com/11372176/209048877-4d99c45e-3e76-4bfa-96ea-7b58929f04d3.png)

HDFView :
![image](https://user-images.githubusercontent.com/11372176/209048937-d8ddaf36-de34-48ad-9551-0fbdc7e013a3.png)

**Comment by batchatco** [comment] 2022-12-24 18:38
Thanks for the report.

I'm not sure your fix is correct though. It doesn't seem to match what the HDF5 specification says.  See https://docs.hdfgroup.org/archive/support/HDF5/doc/H5.format.html, "III.A.1. Disk Format: Level 1A1 - Version 1 B-trees"

Can you please call hdf5.SetLogLevel(3) (without the fix) and then show me the output of the log statements that are just before that?

Ideally, if you can provide me the data file, I can take a look and see if I can reproduce and fix the problem.

**Comment by absolutelyZero** [comment] 2022-12-26 06:01
Thank you for your quick reply.

The output of the log below:

> INFO 2022/12/26 13:25:44 Seek to 0x1bd8
INFO 2022/12/26 13:25:44 key, childaddr 0 10784
INFO 2022/12/26 13:25:46 key, childaddr 112 88874840
INFO 2022/12/26 13:25:49 key, childaddr 144 104684880
INFO 2022/12/26 13:25:49 key, childaddr 32 120494136
INFO 2022/12/26 13:25:49 key, childaddr 200 136303472
INFO 2022/12/26 13:25:49 key, childaddr 232 152112888
INFO 2022/12/26 13:25:49 key, childaddr 256 167922304
INFO 2022/12/26 13:25:49 key, childaddr 288 183731720
INFO 2022/12/26 13:25:49 key, childaddr 48 65161116
INFO 2022/12/26 13:25:49 key, childaddr 360 215351472
INFO 2022/12/26 13:25:49 key, childaddr 392 231160888
INFO 2022/12/26 13:25:49 key, childaddr 416 246970304
INFO 2022/12/26 13:25:49 key, childaddr 448 262779720
INFO 2022/12/26 13:25:49 key, childaddr 64 199542056
INFO 2022/12/26 13:25:49 key, childaddr 528 286493444
INFO 2022/12/26 13:26:02 1: key=32 prevKey=0 size=32 addr=0x2a20
INFO 2022/12/26 13:26:11 2: key=48 prevKey=32 size=16 addr=0x72e9838
INFO 2022/12/26 13:26:11 3: key=64 prevKey=48 size=16 addr=0x3e2479c
INFO 2022/12/26 13:26:11 4: key=112 prevKey=64 size=48 addr=0xbe4c528
INFO 2022/12/26 13:26:11 5: key=144 prevKey=112 size=32 addr=0x54c1f58
INFO 2022/12/26 13:26:11 6: key=200 prevKey=144 size=56 addr=0x63d5d50
INFO 2022/12/26 13:26:11 7: key=232 prevKey=200 size=32 addr=0x81fd370
INFO 2022/12/26 13:26:11 8: key=256 prevKey=232 size=24 addr=0x9110ef8
INFO 2022/12/26 13:26:11 9: key=288 prevKey=256 size=32 addr=0xa024a80
INFO 2022/12/26 13:26:11 10: key=360 prevKey=288 size=72 addr=0xaf38608
INFO 2022/12/26 13:26:11 11: key=392 prevKey=360 size=32 addr=0xcd600b0
INFO 2022/12/26 13:26:11 12: key=416 prevKey=392 size=24 addr=0xdc73c38
INFO 2022/12/26 13:26:11 13: key=448 prevKey=416 size=32 addr=0xeb877c0
INFO 2022/12/26 13:26:11 14: key=528 prevKey=448 size=80 addr=0xfa9b348
INFO 2022/12/26 13:26:11 last: key=8 prevKey=528 size=18446744073709551096 addr=0x11138b04


The last key is 8, less than previous key. This is the place which cause the mistake.

So,I read the section of "III.A.1. Disk Format: Level 1A1 - Version 1 B-trees"  as you said. Then i found some words in the description of  Entries Used , maybe can explain why. 

>  The valid child pointers and keys appear at the beginning of the node and the unused pointers and keys appear at the end of the node. The unused pointers and keys have undefined values


As I undstand,the last key may not be the largest number.

**Comment by batchatco** [comment] 2022-12-26 20:23
Thanks for that information. All of the keys here are valid, because they all have valid pointer values (not undefined, which would be 0xffffffffffffffff). Would it be possible for you to give me this data file? Then I could explore it better.

**Comment by batchatco** [comment] 2022-12-27 07:09
I may have fixed it with 4df5ef74a78ee2313c56104ef5638b6ee3bc28e9.  Please try it and let me know.  I am still interested in seeing your data file, if that is possible.

**Comment by absolutelyZero** [comment] 2022-12-27 12:09
> I may have fixed it with [4df5ef7](https://github.com/batchatco/go-native-netcdf/commit/4df5ef74a78ee2313c56104ef5638b6ee3bc28e9). Please try it and let me know. I am still interested in seeing your data file, if that is possible.

Yes, it works .   I have upload a small data file here(https://github.com/absolutelyZero/go-native-netcdf/blob/master/netcdf/testdata/Result2D.zip ) .

**Comment by batchatco** [comment] 2022-12-31 03:28
Thanks for your data file. It was very helpful. You may delete now if you wish.

My previous fix was not quite correct, but I think I have it right now with ac78786451660b9ffcd2ac30304513215f21dab3.

I would like to add a unit test before closing this bug still though.

**Comment by batchatco** [comment] 2023-01-02 21:53
It turns out to be difficult to add a unit test, so I am going to close this.

**Closed by batchatco** 2023-01-02 21:53 UTC
